### ISSUE TITLE
Error while installing openldap_server 

### ISSUE THREAD

**Issue by IDerr** [ryba-io/ryba-cluster#5]
After fresh install, I had this : 
```
ERROR master3.ryba masson/core/openldap_server { Error: Invalid Exit Code: 255
    at Timeout._onTimeout (D:\Documents\Scripts\bigdata\nikita\lib\system\execute.js:220:17)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
 code: 255 }
```

log/master.log
```
ldap_sasl_bind(SIMPLE): Can't contact LDAP server (-1)

Invalid Exit Code: 255 (ERROR, written by mecano)
Invalid Exit Code: 255 (ERROR, written by mecano)
Invalid Exit Code: 255 (ERROR, written by mecano)
Invalid Exit Code: 255 (ERROR, written by mecano)
Invalid Exit Code: 255 (ERROR, written by mecano)
Invalid Exit Code: 255 (ERROR, written by mecano)
Invalid Exit Code: 255 (ERROR, written by mecano)
Entering ssh.close (DEBUG, written by mecano/lib/ssh/close)
```

After some investigations, I saw that that only the port 389 is open and not the 636

```
[root@master3 vagrant]# netstat -anplt
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address               Foreign Address             State       PID/Program name
tcp        0      0 0.0.0.0:389                 0.0.0.0:*                   LISTEN      14531/slapd
tcp        0      0 0.0.0.0:42603               0.0.0.0:*                   LISTEN      1172/rpc.statd
tcp        0      0 0.0.0.0:111                 0.0.0.0:*                   LISTEN      1150/rpcbind
tcp        0      0 0.0.0.0:22                  0.0.0.0:*                   LISTEN      1478/sshd
tcp        0      0 127.0.0.1:25                0.0.0.0:*                   LISTEN      1568/master
tcp        0      0 10.0.2.15:22                10.0.2.2:51696              ESTABLISHED 1875/sshd
tcp        0      0 :::48895                    :::*                        LISTEN      1172/rpc.statd
tcp        0      0 :::389                      :::*                        LISTEN      14531/slapd
tcp        0      0 :::111                      :::*                        LISTEN      1150/rpcbind
tcp        0      0 :::22                       :::*                        LISTEN      1478/sshd
tcp        0      0 ::1:25                      :::*                        LISTEN      1568/master
```

I fixed the problem by set the value of "SLAPD_LDAPS" to yes in "/etc/sysconfig/ldap"
I don't know if they were changes in defaults values of slapd service.

**Comment by wdavidw** [comment]
is it fixed (I did not forgot about this issue, just not much time at the moment) ?

**Comment by IDerr** [comment]
Yep Fixed :)

**Comment by lucasbak** [comment]
Indeed i did not have any issue when installing redhat 6/7

**Comment by IDerr** [comment]
One more time (windows)

**Comment by wdavidw** [comment]
Did my suggestion in nikita relative to the git configuration helped ?

**Comment by IDerr** [comment]
Yep, but I had two or three minor issues on windows not related to EOL.

**Comment by wdavidw** [comment]
please submit some pull request in such case, none of the contributor work on windows so we cant test it

**Comment by IDerr** [comment]
With pleasure.
